version: "2"
linters:
  enable:
    - copyloopvar
    - errname
    - errorlint
    - forcetypeassert
    - gocritic
    - godot
    - goheader
    - gosec
    - lll
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - predeclared
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    goheader:
      template-path: copyright_header
    gosec:
      config:
        G306: "0o644"
    lll:
      # 145 is just a lax value that does not require too much work to add this check,
      # and we don't want this to be too strict anyway.
      line-length: 145
      tab-width: 4
    makezero:
      always: true
    nolintlint:
      require-explanation: true
      require-specific: true
    staticcheck:
      checks:
        # ST1003 is left out because it is a bit opinionated.
        - -ST1003
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        # A go:generate statement has to be in the same line: https://github.com/golang/go/issues/46050.  
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/runfinch/finch
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
