// Code generated by "stringer -type=Formatter"; DO NOT EDIT.

package flog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Text-0]
	_ = x[TextWithoutTruncation-1]
	_ = x[JSON-2]
}

const _Formatter_name = "TextTextWithoutTruncationJSON"

var _Formatter_index = [...]uint8{0, 4, 25, 29}

func (i Formatter) String() string {
	if i < 0 || i >= Formatter(len(_Formatter_index)-1) {
		return "Formatter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Formatter_name[_Formatter_index[i]:_Formatter_index[i+1]]
}
