// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package vm

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"github.com/onsi/ginkgo/v2"
	"github.com/onsi/gomega"
	"github.com/runfinch/common-tests/command"
	"github.com/runfinch/common-tests/ffs"
	"github.com/runfinch/common-tests/fnet"
	"github.com/runfinch/common-tests/option"
)

// testFinchConfigFile makes sure that DOCKER_CONFIG is properly set to ~/.finch so that related information
// is written to ~/.finch/config.json file.
var testFinchConfigFile = func(o *option.Option, installed bool) {
	ginkgo.Describe("finch config file", func() {
		var vmType string

		ginkgo.BeforeEach(func() {
			if runtime.GOOS == "windows" {
				vmType = "wsl2"
			} else {
				vmType = "vz"
			}
		})

		ginkgo.It("should store login credentials", func() {
			filename := "htpasswd"
			registryImage := "public.ecr.aws/docker/library/registry:2"
			registryContainer := "auth-registry"
			// The htpasswd is generated by
			// `finch run --entrypoint htpasswd public.ecr.aws/docker/library/httpd:2 -Bbn testUser testPassword`.
			// We don't want to generate it on the fly because:
			// 1. Pulling the httpd image can take a long time, sometimes even more 10 seconds.
			// 2. It's unlikely that we will have to update this in the future.
			// 3. It's not the thing we want to validate by the functional tests. We only want the output produced by it.
			//nolint:gosec // This password is only used for testing purpose.
			htpasswd := "testUser:$2y$05$wE0sj3r9O9K9q7R0MXcfPuIerl/06L1IsxXkCuUr3QZ8lHWwicIdS"
			htpasswdDir := filepath.Dir(ffs.CreateTempFile(filename, htpasswd))
			ginkgo.DeferCleanup(os.RemoveAll, htpasswdDir)
			port := fnet.GetFreePort()
			containerID := command.StdoutStr(o, "run",
				"-dp", fmt.Sprintf("%d:5000", port),
				"--name", registryContainer,
				"-v", fmt.Sprintf("%s:/auth", htpasswdDir),
				"-e", "REGISTRY_AUTH=htpasswd",
				"-e", "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm",
				"-e", fmt.Sprintf("REGISTRY_AUTH_HTPASSWD_PATH=/auth/%s", filename),
				registryImage)
			ginkgo.DeferCleanup(command.Run, o, "rmi", "-f", registryImage)
			ginkgo.DeferCleanup(command.Run, o, "rm", "-f", registryContainer)
			for command.StdoutStr(o, "inspect", "-f", "{{.State.Running}}", containerID) != "true" {
				time.Sleep(1 * time.Second)
			}
			time.Sleep(10 * time.Second)
			registry := fmt.Sprintf(`localhost:%d`, port)
			command.Run(o, "login", registry, "-u", "testUser", "-p", "testPassword")

			var finchRootDir string
			var err error
			if runtime.GOOS == "windows" {
				finchRootDir = os.Getenv("LOCALAPPDATA")
			} else {
				finchRootDir, err = os.UserHomeDir()
				gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			}

			configPath := filepath.Join(finchRootDir, ".finch", "config.json")
			configContent, err := os.ReadFile(filepath.Clean(configPath))
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())

			gomega.Expect(string(configContent)).Should(gomega.ContainSubstring(registry))
			command.Run(o, "logout", registry)

			configContent, err = os.ReadFile(filepath.Clean(configPath))
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(string(configContent)).ShouldNot(gomega.ContainSubstring(registry))
		})

		ginkgo.It("should refresh config.json if creds_helpers is not set in finch.yaml, but config.json is configured with credsStore", func() {
			resetVM(o)
			resetDisks(o, installed)
			writeFile(finchConfigFilePath, []byte(fmt.Sprintf("cpus: 6\nmemory: 4GiB\nvmType: %s\nrosetta: true", vmType)))
			writeFile(finchConfigJSONPath, []byte(`{"credsStore":"ecr-login"}`))
			command.New(o, virtualMachineRootCmd, "init").WithoutCheckingExitCode().WithTimeoutInSeconds(160).Run()
			gomega.Expect(string(readFile(finchConfigJSONPath))).Should(gomega.Equal(`{"auths":{}}`))
		})
	})
}
