// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch/pkg/command (interfaces: Creator)
//
// Generated by this command:
//
//	mockgen -copyright_file=../../copyright_header -destination=../mocks/command_command_creator.go -package=mocks -mock_names Creator=CommandCreator . Creator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	command "github.com/runfinch/finch/pkg/command"
	gomock "go.uber.org/mock/gomock"
)

// CommandCreator is a mock of Creator interface.
type CommandCreator struct {
	ctrl     *gomock.Controller
	recorder *CommandCreatorMockRecorder
	isgomock struct{}
}

// CommandCreatorMockRecorder is the mock recorder for CommandCreator.
type CommandCreatorMockRecorder struct {
	mock *CommandCreator
}

// NewCommandCreator creates a new mock instance.
func NewCommandCreator(ctrl *gomock.Controller) *CommandCreator {
	mock := &CommandCreator{ctrl: ctrl}
	mock.recorder = &CommandCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CommandCreator) EXPECT() *CommandCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *CommandCreator) Create(name string, args ...string) command.Command {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(command.Command)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *CommandCreatorMockRecorder) Create(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*CommandCreator)(nil).Create), varargs...)
}
