// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch/pkg/path (interfaces: FinchFinderDeps)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// FinchFinderDeps is a mock of FinchFinderDeps interface.
type FinchFinderDeps struct {
	ctrl     *gomock.Controller
	recorder *FinchFinderDepsMockRecorder
}

// FinchFinderDepsMockRecorder is the mock recorder for FinchFinderDeps.
type FinchFinderDepsMockRecorder struct {
	mock *FinchFinderDeps
}

// NewFinchFinderDeps creates a new mock instance.
func NewFinchFinderDeps(ctrl *gomock.Controller) *FinchFinderDeps {
	mock := &FinchFinderDeps{ctrl: ctrl}
	mock.recorder = &FinchFinderDepsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FinchFinderDeps) EXPECT() *FinchFinderDepsMockRecorder {
	return m.recorder
}

// Env mocks base method.
func (m *FinchFinderDeps) Env(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *FinchFinderDepsMockRecorder) Env(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*FinchFinderDeps)(nil).Env), arg0)
}

// EvalSymlinks mocks base method.
func (m *FinchFinderDeps) EvalSymlinks(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvalSymlinks", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvalSymlinks indicates an expected call of EvalSymlinks.
func (mr *FinchFinderDepsMockRecorder) EvalSymlinks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvalSymlinks", reflect.TypeOf((*FinchFinderDeps)(nil).EvalSymlinks), arg0)
}

// Executable mocks base method.
func (m *FinchFinderDeps) Executable() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Executable")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Executable indicates an expected call of Executable.
func (mr *FinchFinderDepsMockRecorder) Executable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Executable", reflect.TypeOf((*FinchFinderDeps)(nil).Executable))
}

// FilePathJoin mocks base method.
func (m *FinchFinderDeps) FilePathJoin(arg0 ...string) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FilePathJoin", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// FilePathJoin indicates an expected call of FilePathJoin.
func (mr *FinchFinderDepsMockRecorder) FilePathJoin(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilePathJoin", reflect.TypeOf((*FinchFinderDeps)(nil).FilePathJoin), arg0...)
}

// GetUserHome mocks base method.
func (m *FinchFinderDeps) GetUserHome() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHome")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHome indicates an expected call of GetUserHome.
func (mr *FinchFinderDepsMockRecorder) GetUserHome() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHome", reflect.TypeOf((*FinchFinderDeps)(nil).GetUserHome))
}
