// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch/pkg/lima/wrapper (interfaces: LimaWrapper)

// Package mocks is a generated GoMock package.
package mocks

import (
	user "os/user"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLimaWrapper is a mock of LimaWrapper interface.
type MockLimaWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockLimaWrapperMockRecorder
}

// MockLimaWrapperMockRecorder is the mock recorder for MockLimaWrapper.
type MockLimaWrapperMockRecorder struct {
	mock *MockLimaWrapper
}

// NewMockLimaWrapper creates a new mock instance.
func NewMockLimaWrapper(ctrl *gomock.Controller) *MockLimaWrapper {
	mock := &MockLimaWrapper{ctrl: ctrl}
	mock.recorder = &MockLimaWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimaWrapper) EXPECT() *MockLimaWrapperMockRecorder {
	return m.recorder
}

// LimaUser mocks base method.
func (m *MockLimaWrapper) LimaUser(arg0 bool) *user.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LimaUser", arg0)
	ret0, _ := ret[0].(*user.User)
	return ret0
}

// LimaUser indicates an expected call of LimaUser.
func (mr *MockLimaWrapperMockRecorder) LimaUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LimaUser", reflect.TypeOf((*MockLimaWrapper)(nil).LimaUser), arg0)
}
