// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch/pkg/command (interfaces: NerdctlCmdCreatorSystemDeps)

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// NerdctlCmdCreatorSystemDeps is a mock of NerdctlCmdCreatorSystemDeps interface.
type NerdctlCmdCreatorSystemDeps struct {
	ctrl     *gomock.Controller
	recorder *NerdctlCmdCreatorSystemDepsMockRecorder
}

// NerdctlCmdCreatorSystemDepsMockRecorder is the mock recorder for NerdctlCmdCreatorSystemDeps.
type NerdctlCmdCreatorSystemDepsMockRecorder struct {
	mock *NerdctlCmdCreatorSystemDeps
}

// NewNerdctlCmdCreatorSystemDeps creates a new mock instance.
func NewNerdctlCmdCreatorSystemDeps(ctrl *gomock.Controller) *NerdctlCmdCreatorSystemDeps {
	mock := &NerdctlCmdCreatorSystemDeps{ctrl: ctrl}
	mock.recorder = &NerdctlCmdCreatorSystemDepsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *NerdctlCmdCreatorSystemDeps) EXPECT() *NerdctlCmdCreatorSystemDepsMockRecorder {
	return m.recorder
}

// Env mocks base method.
func (m *NerdctlCmdCreatorSystemDeps) Env(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *NerdctlCmdCreatorSystemDepsMockRecorder) Env(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*NerdctlCmdCreatorSystemDeps)(nil).Env), arg0)
}

// Environ mocks base method.
func (m *NerdctlCmdCreatorSystemDeps) Environ() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Environ")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Environ indicates an expected call of Environ.
func (mr *NerdctlCmdCreatorSystemDepsMockRecorder) Environ() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Environ", reflect.TypeOf((*NerdctlCmdCreatorSystemDeps)(nil).Environ))
}

// Stderr mocks base method.
func (m *NerdctlCmdCreatorSystemDeps) Stderr() *os.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stderr")
	ret0, _ := ret[0].(*os.File)
	return ret0
}

// Stderr indicates an expected call of Stderr.
func (mr *NerdctlCmdCreatorSystemDepsMockRecorder) Stderr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stderr", reflect.TypeOf((*NerdctlCmdCreatorSystemDeps)(nil).Stderr))
}

// Stdin mocks base method.
func (m *NerdctlCmdCreatorSystemDeps) Stdin() *os.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stdin")
	ret0, _ := ret[0].(*os.File)
	return ret0
}

// Stdin indicates an expected call of Stdin.
func (mr *NerdctlCmdCreatorSystemDepsMockRecorder) Stdin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stdin", reflect.TypeOf((*NerdctlCmdCreatorSystemDeps)(nil).Stdin))
}

// Stdout mocks base method.
func (m *NerdctlCmdCreatorSystemDeps) Stdout() *os.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stdout")
	ret0, _ := ret[0].(*os.File)
	return ret0
}

// Stdout indicates an expected call of Stdout.
func (mr *NerdctlCmdCreatorSystemDepsMockRecorder) Stdout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stdout", reflect.TypeOf((*NerdctlCmdCreatorSystemDeps)(nil).Stdout))
}
