// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch/cmd/finch (interfaces: VMAutoStarter)
//
// Generated by this command:
//
//	mockgen -copyright_file=../../copyright_header -destination=../../pkg/mocks/vm_auto_starter.go -package=mocks -mock_names VMAutoStarter=VMAutoStarter . VMAutoStarter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// VMAutoStarter is a mock of VMAutoStarter interface.
type VMAutoStarter struct {
	ctrl     *gomock.Controller
	recorder *VMAutoStarterMockRecorder
	isgomock struct{}
}

// VMAutoStarterMockRecorder is the mock recorder for VMAutoStarter.
type VMAutoStarterMockRecorder struct {
	mock *VMAutoStarter
}

// NewVMAutoStarter creates a new mock instance.
func NewVMAutoStarter(ctrl *gomock.Controller) *VMAutoStarter {
	mock := &VMAutoStarter{ctrl: ctrl}
	mock.recorder = &VMAutoStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *VMAutoStarter) EXPECT() *VMAutoStarterMockRecorder {
	return m.recorder
}

// EnsureVMRunning mocks base method.
func (m *VMAutoStarter) EnsureVMRunning() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureVMRunning")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureVMRunning indicates an expected call of EnsureVMRunning.
func (mr *VMAutoStarterMockRecorder) EnsureVMRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureVMRunning", reflect.TypeOf((*VMAutoStarter)(nil).EnsureVMRunning))
}
