name: Sync Submodules and Dependencies

# Pulls changes from the main branch of submodules daily at 9:00 UTC and opens a PR.
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  # This is required for configure-aws-credentials to request an OIDC JWT ID token to access AWS resources later on.
  # More info: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: sync-submodules-and-deps-session

      - name: Update submodules
        run: |
          git submodule update --remote

      - name: Create PR
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: true
          title: 'build(deps): Bump submodules and dependencies'
          body: >
            Bump for Finch's dependencies.

            Updates finch-core submodule which defines the core dependencies for Finch on each respective
            platform such as: operating system images and Lima bundle (Lima version and it's dependencies)
            as `lima-and-qemu.macos-*.*.tar.gz` archives.

            Since updating the Lima version may also update the default version of the `nerdctl-full`
            archive (which contains nerdctl, containerd, buildkit, etc.), this may require a manual
            update to
            [`e2e/vm/version_test.go`](https://github.com/runfinch/finch/tree/create-pull-request/patch/e2e/vm/version_test.go).

            To do so, checkout this PR branch locally, add a new commit to the branch,
            and push back to the branch:

              ```bash
              git fetch --all
              git switch create-pull-request/patch
              # make changes
              git add e2e/vm/version_test.go
              git commit -s "update dependency versions in version test"
              git push
              ```
